// <auto-generated />
using System;
using AuthService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511185800_AddEstudiantesSeed")]
    partial class AddEstudiantesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Descripcion = "Administrador del sistema",
                            NombreRol = "Admin"
                        },
                        new
                        {
                            IdRol = 2,
                            Descripcion = "Guardia de seguridad",
                            NombreRol = "Guardia"
                        },
                        new
                        {
                            IdRol = 3,
                            Descripcion = "Estudiante de la UTA",
                            NombreRol = "Estudiante"
                        },
                        new
                        {
                            IdRol = 4,
                            Descripcion = "Docente de la UTA",
                            NombreRol = "Docente"
                        });
                });

            modelBuilder.Entity("AuthService.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Facultad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            ContrasenaHash = "$2a$11$cN//UnlEIFmdlC6q6mZuOu42CKP3irBnaMtI8ZqAIMIxWFLNb8OZ.",
                            Correo = "admin@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "Administración Central",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 1,
                            Nombre = "Administrador UTA"
                        },
                        new
                        {
                            IdUsuario = 2,
                            ContrasenaHash = "$2a$11$v/3L5JzIPWvSuVmL/VQoEOqX1BKSxdwwSVtd5CNd.doJXl2EqHDri",
                            Correo = "guardia1@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "Seguridad UTA",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 2,
                            Nombre = "Carlos Guardia"
                        },
                        new
                        {
                            IdUsuario = 3,
                            ContrasenaHash = "$2a$11$v/3L5JzIPWvSuVmL/VQoEOqX1BKSxdwwSVtd5CNd.doJXl2EqHDri",
                            Correo = "guardia2@uta.edu.ec",
                            Disponible = false,
                            Estado = "Activo",
                            Facultad = "Seguridad UTA",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 2,
                            Nombre = "Pedro Guardia"
                        },
                        new
                        {
                            IdUsuario = 4,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "wilson@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "Facultad de Ingeniería en Sistemas",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Wilson Pillapa"
                        },
                        new
                        {
                            IdUsuario = 5,
                            ContrasenaHash = "$2a$11$ylhM/4w1dLl.mIqVydpR2OmB8/Jw7VWlLuDkA4eKcNLNC7rTvE5c2",
                            Correo = "docente@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "Facultad de Ingeniería en Sistemas",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 4,
                            Nombre = "Juan Docente"
                        },
                        new
                        {
                            IdUsuario = 6,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante1@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 1"
                        },
                        new
                        {
                            IdUsuario = 7,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante2@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 2"
                        },
                        new
                        {
                            IdUsuario = 8,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante3@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 3"
                        },
                        new
                        {
                            IdUsuario = 9,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante4@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 4"
                        },
                        new
                        {
                            IdUsuario = 10,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante5@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 5"
                        },
                        new
                        {
                            IdUsuario = 11,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante6@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 6"
                        },
                        new
                        {
                            IdUsuario = 12,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante7@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 7"
                        },
                        new
                        {
                            IdUsuario = 13,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante8@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 8"
                        },
                        new
                        {
                            IdUsuario = 14,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante9@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 9"
                        },
                        new
                        {
                            IdUsuario = 15,
                            ContrasenaHash = "$2a$11$CLFV2MnHCrdx1a5kgYlOcOrKgq.UpTtg3IXWtLEiOUxEa2qq0eKpW",
                            Correo = "estudiante10@uta.edu.ec",
                            Disponible = true,
                            Estado = "Activo",
                            Facultad = "FISEI",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRol = 3,
                            Nombre = "Estudiante 10"
                        });
                });

            modelBuilder.Entity("AuthService.Models.Usuario", b =>
                {
                    b.HasOne("AuthService.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AuthService.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
