// <auto-generated />
using System;
using IncidentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncidentService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524153711_AddCamarasTable")]
    partial class AddCamarasTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncidentService.Models.Camara", b =>
                {
                    b.Property<int>("IdCamara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCamara"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdZona")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlStream")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdCamara");

                    b.HasIndex("IdZona");

                    b.ToTable("Camaras");

                    b.HasData(
                        new
                        {
                            IdCamara = 1,
                            Estado = "Activa",
                            IdZona = 1,
                            Latitud = -1.2490m,
                            Longitud = -78.6166m,
                            Nombre = "Cámara Entrada Principal",
                            UrlStream = "https://www.w3schools.com/html/mov_bbb.mp4"
                        },
                        new
                        {
                            IdCamara = 2,
                            Estado = "Activa",
                            IdZona = 2,
                            Latitud = -1.2497m,
                            Longitud = -78.6170m,
                            Nombre = "Cámara Admin Externa",
                            UrlStream = "https://www.w3schools.com/html/movie.mp4"
                        },
                        new
                        {
                            IdCamara = 3,
                            Estado = "Mantenimiento",
                            IdZona = 3,
                            Latitud = -1.2486m,
                            Longitud = -78.6181m,
                            Nombre = "Cámara Salud Interna",
                            UrlStream = "https://www.w3schools.com/html/mov_bbb.mp4"
                        },
                        new
                        {
                            IdCamara = 4,
                            Estado = "Activa",
                            IdZona = 4,
                            Latitud = -1.2503m,
                            Longitud = -78.6160m,
                            Nombre = "Cámara Lab FCI",
                            UrlStream = "https://www.w3schools.com/html/movie.mp4"
                        });
                });

            modelBuilder.Entity("IncidentService.Models.Incidente", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncidente"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdZona")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoIncidente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdIncidente");

                    b.HasIndex("IdZona");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("IncidentService.Models.Zona", b =>
                {
                    b.Property<int>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZona"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CoordenadasPoligono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdZona");

                    b.ToTable("Zonas");

                    b.HasData(
                        new
                        {
                            IdZona = 1,
                            Activa = true,
                            Descripcion = "Facultad de Arquitectura y Humanidades",
                            Latitud = -1.2491m,
                            Longitud = -78.6167m,
                            Nombre = "Zona 1 — Arquitectura / Humanidades"
                        },
                        new
                        {
                            IdZona = 2,
                            Activa = true,
                            Descripcion = "Facultad de Ciencias Administrativas",
                            Latitud = -1.2498m,
                            Longitud = -78.6172m,
                            Nombre = "Zona 2 — Administración"
                        },
                        new
                        {
                            IdZona = 3,
                            Activa = true,
                            Descripcion = "Facultad de Ciencias de la Salud",
                            Latitud = -1.2485m,
                            Longitud = -78.6180m,
                            Nombre = "Zona 3 — Ciencias de la Salud"
                        },
                        new
                        {
                            IdZona = 4,
                            Activa = true,
                            Descripcion = "Facultad de Ingeniería y FCI",
                            Latitud = -1.2502m,
                            Longitud = -78.6162m,
                            Nombre = "Zona 4 — Ingeniería / FCI"
                        });
                });

            modelBuilder.Entity("IncidentService.Models.Camara", b =>
                {
                    b.HasOne("IncidentService.Models.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("IdZona");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("IncidentService.Models.Incidente", b =>
                {
                    b.HasOne("IncidentService.Models.Zona", "Zona")
                        .WithMany("Incidentes")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("IncidentService.Models.Zona", b =>
                {
                    b.Navigation("Incidentes");
                });
#pragma warning restore 612, 618
        }
    }
}
