// <auto-generated />
using System;
using IncidentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncidentService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611000613_AgregarTurnosYReportes")]
    partial class AgregarTurnosYReportes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncidentService.Models.Camara", b =>
                {
                    b.Property<int>("IdCamara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCamara"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdZona")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlStream")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdCamara");

                    b.HasIndex("IdZona");

                    b.ToTable("Camaras");

                    b.HasData(
                        new
                        {
                            IdCamara = 1,
                            Estado = "Activa",
                            IdZona = 1,
                            Latitud = -1.2674m,
                            Longitud = -78.6248m,
                            Nombre = "Cámara Entrada Principal",
                            UrlStream = "https://www.w3schools.com/html/mov_bbb.mp4"
                        },
                        new
                        {
                            IdCamara = 2,
                            Estado = "Activa",
                            IdZona = 2,
                            Latitud = -1.2697m,
                            Longitud = -78.6233m,
                            Nombre = "Cámara Admin Externa",
                            UrlStream = "https://www.w3schools.com/html/movie.mp4"
                        },
                        new
                        {
                            IdCamara = 3,
                            Estado = "Mantenimiento",
                            IdZona = 3,
                            Latitud = -1.2676m,
                            Longitud = -78.6235m,
                            Nombre = "Cámara Salud Interna",
                            UrlStream = "https://www.w3schools.com/html/mov_bbb.mp4"
                        },
                        new
                        {
                            IdCamara = 4,
                            Estado = "Activa",
                            IdZona = 4,
                            Latitud = -1.2695m,
                            Longitud = -78.6251m,
                            Nombre = "Cámara Lab FCI",
                            UrlStream = "https://www.w3schools.com/html/movie.mp4"
                        });
                });

            modelBuilder.Entity("IncidentService.Models.Incidente", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncidente"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuardiaAsignado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdZona")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoIncidente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdIncidente");

                    b.HasIndex("IdZona");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("IncidentService.Models.ReporteGuardia", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraIncidente")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdGuardia")
                        .HasColumnType("int");

                    b.Property<int?>("IdTurno")
                        .HasColumnType("int");

                    b.Property<int?>("IdZona")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("NombreGuardia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroReporte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdTurno");

                    b.HasIndex("IdZona");

                    b.ToTable("ReportesGuardia");
                });

            modelBuilder.Entity("IncidentService.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdGuardia")
                        .HasColumnType("int");

                    b.Property<string>("NombreGuardia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreTurno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTurno");

                    b.ToTable("Turnos");

                    b.HasData(
                        new
                        {
                            IdTurno = 1,
                            Activo = true,
                            DiaSemana = "Todos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new TimeSpan(0, 13, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 7, 0, 0, 0),
                            IdGuardia = 0,
                            NombreGuardia = "",
                            NombreTurno = "Turno Mañana"
                        },
                        new
                        {
                            IdTurno = 2,
                            Activo = true,
                            DiaSemana = "Todos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 13, 0, 0, 0),
                            IdGuardia = 0,
                            NombreGuardia = "",
                            NombreTurno = "Turno Tarde"
                        },
                        new
                        {
                            IdTurno = 3,
                            Activo = true,
                            DiaSemana = "Todos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new TimeSpan(0, 7, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 19, 0, 0, 0),
                            IdGuardia = 0,
                            NombreGuardia = "",
                            NombreTurno = "Turno Noche"
                        });
                });

            modelBuilder.Entity("IncidentService.Models.Zona", b =>
                {
                    b.Property<int>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZona"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CoordenadasPoligono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdZona");

                    b.ToTable("Zonas");

                    b.HasData(
                        new
                        {
                            IdZona = 1,
                            Activa = true,
                            Descripcion = "Facultad de Arquitectura y Humanidades",
                            Latitud = -1.2674m,
                            Longitud = -78.6248m,
                            Nombre = "Zona 1 — Arquitectura / Humanidades"
                        },
                        new
                        {
                            IdZona = 2,
                            Activa = true,
                            Descripcion = "Facultad de Ciencias Administrativas",
                            Latitud = -1.2697m,
                            Longitud = -78.6233m,
                            Nombre = "Zona 2 — Administración"
                        },
                        new
                        {
                            IdZona = 3,
                            Activa = true,
                            Descripcion = "Facultad de Ciencias de la Salud",
                            Latitud = -1.2676m,
                            Longitud = -78.6235m,
                            Nombre = "Zona 3 — Ciencias de la Salud"
                        },
                        new
                        {
                            IdZona = 4,
                            Activa = true,
                            Descripcion = "Facultad de Ingeniería y FCI",
                            Latitud = -1.2695m,
                            Longitud = -78.6251m,
                            Nombre = "Zona 4 — Ingeniería / FCI"
                        });
                });

            modelBuilder.Entity("IncidentService.Models.Camara", b =>
                {
                    b.HasOne("IncidentService.Models.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("IdZona");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("IncidentService.Models.Incidente", b =>
                {
                    b.HasOne("IncidentService.Models.Zona", "Zona")
                        .WithMany("Incidentes")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("IncidentService.Models.ReporteGuardia", b =>
                {
                    b.HasOne("IncidentService.Models.Turno", "Turno")
                        .WithMany("Reportes")
                        .HasForeignKey("IdTurno");

                    b.HasOne("IncidentService.Models.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("IdZona");

                    b.Navigation("Turno");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("IncidentService.Models.Turno", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("IncidentService.Models.Zona", b =>
                {
                    b.Navigation("Incidentes");
                });
#pragma warning restore 612, 618
        }
    }
}
